services:
    jms_serializer.object_constructor:
        alias: jms_serializer.initialized_object_constructor
        public: false
    jms_serializer.initialized_object_constructor:
        class:        Lube\GeneratorBundle\Services\InitializedObjectConstructor
        arguments:    ["@jms_serializer.doctrine_object_constructor"]
    lube_generator.association_immutabilizer:
        class:        Lube\GeneratorBundle\Services\ImmutableAssociationService
        arguments:    ["@doctrine.orm.default_entity_manager"]